#!/bin/bash

set -e

TARGET="x86_64-w64-mingw32"

# packages
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  automake \
  bison \
  bzip2 \
  ca-certificates \
  curl \
  file \
  flex \
  g++ \
  gawk \
  gdb \
  git \
  gperf \
  help2man \
  libncurses-dev \
  libssl-dev \
  libtool-bin \
  make \
  patch \
  pkg-config \
  python3 \
  rsync \
  texinfo \
  unzip \
  wget \
  xz-utils \
  ccache

# 设置 ccache
export CCACHE_DIR="$HOME/.ccache"
export PATH="/usr/lib/ccache:$PATH"
ccache --max-size=2G

# patch
#pushd builder
#for i in ../targets/${TARGET}/*; do
#    if [[ $i == *.patch ]]; then
#        patch -Np1 -i $i
#    fi
#done
#popd

# crosstool-ng
echo "编译ct-ng版本"
if [ ! -e /usr/bin/ct-ng ]; then
    pushd builder
    ./bootstrap
    ./configure --prefix=/usr
    make -j`nproc`
    sudo make install
    popd
fi
# build
sudo mkdir -p /opt
sudo chmod 0777 /opt
mkdir -p build
cp targets/${TARGET}/config build/.config
pushd build
ct-ng olddefconfig
echo "显示原版"
#cat $(pwd)/.config
echo "显示结束"

# 更新gmp
sed -i "s/^CT_GMP_VERSION=\"[^\"]*\"/CT_GMP_VERSION=\"6.3.0\"/" $(pwd)/.config
sed -i "s/^CT_GMP_V_6_2=y/# CT_GMP_V_6_2 is not set/" $(pwd)/.config
sed -i '/^# CT_GMP_V_6_2 is not set/iCT_GMP_V_6_3=y' $(pwd)/.config

# 更新ISL 
sed -i "s/^CT_ISL_VERSION=\"[^\"]*\"/CT_ISL_VERSION=\"0.27\"/" $(pwd)/.config
sed -i "s/^CT_ISL_V_0_26=y/# CT_ISL_V_0_26 is not set/" $(pwd)/.config
sed -i '/^# CT_ISL_V_0_26 is not set/iCT_ISL_V_0_27=y' $(pwd)/.config

# 更新binutils
sed -i "s/^CT_BINUTILS_VERSION=\"[^\"]*\"/CT_BINUTILS_VERSION=\"2.44\"/" $(pwd)/.config
sed -i "s/^CT_BINUTILS_V_2_43=y/# CT_BINUTILS_V_2_43 is not set/" $(pwd)/.config
sed -i '/^# CT_BINUTILS_V_2_43 is not set/i CT_BINUTILS_V_2_44=y' $(pwd)/.config

# mingw-w64最新版
sed -i "s|^CT_MINGW_W64_MIRRORS=.*|CT_MINGW_W64_MIRRORS=\"https://github.com/mingw-w64/mingw-w64/archive\"|" $(pwd)/.config
sed -i "s/^CT_MINGW_W64_ARCHIVE_FORMATS=\".*\"/CT_MINGW_W64_ARCHIVE_FORMATS=\".tar.gz\"/" $(pwd)/.config
sed -i "s/^CT_MINGW_W64_ARCHIVE_FILENAME=\".*\"/CT_MINGW_W64_ARCHIVE_FILENAME=\"mingw-w64-master\"/" $(pwd)/.config
sed -i "s/^CT_MINGW_W64_ARCHIVE_DIRNAME=\".*\"/CT_MINGW_W64_ARCHIVE_DIRNAME=\"mingw-w64-master\"/" $(pwd)/.config
sed -i "s/^CT_VERIFY_DOWNLOAD_SIGNATURE=y/# CT_VERIFY_DOWNLOAD_SIGNATURE is not set/" $(pwd)/.config
sed -i "s/^CT_MINGW_W64_SIGNATURE_FORMAT=\".*\"/CT_MINGW_W64_SIGNATURE_FORMAT=\"\"/" $(pwd)/.config

echo "显示新版"
cat $(pwd)/.config
echo "显示结束"

ct-ng build.$(nproc)
popd

# 删除临时文件
sudo mv /opt/x-tools/${TARGET} .
sudo chown -R root:root ${TARGET}
sudo tar -cJvf ${TARGET}.tar.xz ${TARGET}
sudo sha256sum ${TARGET}.tar.xz | awk '{ print $1 }' > ${TARGET}.tar.xz.sha256

# 输出 ccache 使用情况
ccache --show-stats
