#!/bin/bash

set -e

TARGET=$1

# packages
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  gdb \
  gperf \
  help2man \
  libssl-dev \
  libtool-bin

# patch
pushd builder
git reset --hard HEAD
git clean -fd
for i in ../targets/${TARGET}/*; do
    if [[ $i == *.patch ]]; then
        patch -Np1 -i $i
    fi
done
popd

# crosstool-ng
sudo mkdir -p /opt
sudo chmod 0777 /opt
sudo rm -rf /opt/ct-ng
pushd builder
./bootstrap
./configure --prefix=/opt/ct-ng
make -j`nproc`
sudo make install
popd

# build
rm -rf build
mkdir -p build
cp targets/${TARGET}/config build/.config
pushd build
/opt/ct-ng/bin/ct-ng olddefconfig

echo "显示原版"
cat $(pwd)/.config
echo "显示结束"


echo "显示新版"
cat $(pwd)/.config
echo "显示结束"


/opt/ct-ng/bin/ct-ng build
popd

# tarball
sudo mv /opt/x-tools/${TARGET} .
sudo chown -R root:root ${TARGET}
sudo tar -cJvf ${TARGET}-1.tar.xz ${TARGET}
sudo sha256sum ${TARGET}-1.tar.xz | awk '{ print $1 }' > ${TARGET}-1.tar.xz.sha256
