name: Check Versions and Create Release (Version.md only)

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  release:
    types:
      - released
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_and_release:
    name: Check Versions and Create Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Check Versions Script
        run: |
          chmod +x $GITHUB_WORKSPACE/check-version.sh
          $GITHUB_WORKSPACE/check-version.sh

      - name: Upload version.md Artifact
        uses: actions/upload-artifact@v4
        with:
          name: version-md
          path: ${{ github.workspace }}/version.md
          retention-days: 1

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: Check Version
          name: version
          allowUpdates: true
          bodyFile: ${{ github.workspace }}/version.md
          token: ${{ secrets.GITHUB_TOKEN }}
