name: Auto Update Submodules
on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间午夜更新
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git add builder
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git commit -m "Auto-update builder submodule" || echo "No changes"
          git push
