name: Auto Update Submodules
on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间午夜更新
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Force update submodules
        run: |
          git submodule foreach --recursive 'git reset --hard'
          git submodule update --init --remote --force --recursive
          git add builder
          
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@users.noreply.github.com"
            git commit -m "Auto-update builder submodule"
            git push
          else
            echo "No changes to commit"
          fi
